# Generated by Django 3.1.4 on 2020-12-09 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('idKlienta', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('numerTelefonu', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=45)),
                ('haslo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'klienci',
            },
        ),
        migrations.CreateModel(
            name='Przedmioty',
            fields=[
                ('idPrzedmiotu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=11)),
                ('opis', models.TextField()),
                ('widoczny', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'przedmioty',
            },
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('idZamowienia', models.AutoField(primary_key=True, serialize=False)),
                ('dataZamowienia', models.DateTimeField(default=datetime.date.today)),
                ('status', models.CharField(max_length=255)),
                ('idKlienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lombard.klienci')),
                ('idPrzedmiotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lombard.przedmioty')),
            ],
            options={
                'db_table': 'zamowienia',
            },
        ),
    ]
