# Generated by Django 3.1.4 on 2021-01-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lombard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienia',
            name='opis',
        ),
    ]
