# Generated by Django 3.1.4 on 2020-12-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lombard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='idKlienta',
            field=models.ForeignKey(db_column='idKlienta', on_delete=django.db.models.deletion.CASCADE, to='Lombard.klienci'),
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='idPrzedmiotu',
            field=models.ForeignKey(db_column='idPrzedmiotu', on_delete=django.db.models.deletion.CASCADE, to='Lombard.przedmioty'),
        ),
    ]
