# Generated by Django 3.1.4 on 2021-01-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lombard', '0003_remove_przedmioty_opis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przedmioty',
            name='cena',
        ),
    ]
