# Generated by Django 3.1.4 on 2021-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lombard', '0004_remove_przedmioty_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='przedmioty',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='przedmioty',
            name='opis',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
