# Generated by Django 3.1.4 on 2021-01-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lombard', '0005_auto_20210127_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przedmioty',
            name='opis',
        ),
        migrations.AlterField(
            model_name='przedmioty',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
