# Generated by Django 3.1.4 on 2021-02-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lombard', '0006_auto_20210130_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='przedmioty',
            name='opis',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
